# Generated by Django 4.1.7 on 2023-08-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.IntegerField()),
                ('employeeName', models.CharField(max_length=50)),
                ('employeeSalary', models.FloatField()),
            ],
        ),
    ]
